# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: reactoragent
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/daemon/daemon.go
    id: daemon
    binary: daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - config/example.conf
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: leonwright
      name: homebrew-tap
    folder: Formula
    homepage:  https://nerderbur.tech
    description: Supercharge your development server.
    caveats: "1. Edit the default.conf file in #{prefix}\n"
    # So you can `brew test` your formula.
    # Default is empty.
    install: |-
      prefix.install Dir["*"]
    post_install: |
      if !(File.exist?((etc/"reactoragent.conf"))) then
        etc.mkpath
        etc.install "config/example.conf" => "reactoragent.conf"
      end
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>com.nerderbur.tech</string>

            <key>RunAtLoad</key>
            <true/>

            <key>KeepAlive</key>
            <true/>

            <key>ProgramArguments</key>
            <array>
                <string>#{bin}/daemon</string>
                <string>-config</string>
                <string>#{prefix}/reactoragent.conf</string>
            </array>

            <key>StandardOutPath</key>
            <string>/tmp/log/reactoragent.log</string>

            <key>StandardErrorPath</key>
            <string>/tmp/log/reactoragent.log</string>
        </dict>
      </plist>
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://nerderbur.tech
    description: Supercharge your development server.
    maintainer: Leon Wright <leonwrightscode@gmail.com>
    license: MIT
    vendor: Nerderbur
    contents:
      - src: ./config/example.conf
        dst: /etc/reactoragent/example.conf
    formats:
    - apk
    - deb
    - rpm
    dependencies:
    - git
    recommends:
    - golang
snapcrafts:
  - id: reactoragent
    publish: true
    description: Reactor Agent is a simple daemon application that instantly transforms your server into a development environment with all the tools you need to instantly start developing applications from anywhere.
    summary: Supercharge your cloud development environment.
    grade: stable
    license: MIT
    base: core18
    extra_files:
      - source: ./config/example.conf
        destination: /etc/reactoragent/default.conf
        mode: 0755
    apps:
      # The name of the app must be the same name as the binary built or the snapcraft name.
      drumroll:
        plugs: ["network", "system-files"]
        daemon: simple
        command: ./daemon
        args: -config /etc/reactoragent/default.conf
        restart_condition: "always"