# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: reactoragent
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/daemon/daemon.go
    id: daemon
    binary: daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - config/example.conf
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: leonwright
      name: homebrew-tap
    folder: Formula
    homepage:  https://nerderbur.tech
    description: Supercharge your development server.
    caveats: "1. Edit the example.conf file in /usr/local/etc/reactoragent\n2. Rename example.conf to default.conf"
    # So you can `brew test` your formula.
    # Default is empty.
    install: |-
      bin.install "daemon"
      etc.mkpath
      mkdir "#{etc}/reactorapp"
      etc.install "config/example.conf" => "reactorapp/example.conf"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://nerderbur.tech
    description: Supercharge your development server.
    maintainer: Leon Wright <leonwrightscode@gmail.com>
    license: MIT
    vendor: Nerderbur
    contents:
      - src: ./config/example.conf
        dst: /etc/reactoragent/example.conf
    formats:
    - apk
    - deb
    - rpm
    dependencies:
    - git
    recommends:
    - golang
